name: ci
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Super-linter
      uses: super-linter/super-linter@v6.6.0
      env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker image
      run: |
        docker build -t weatherapp .
        
    - name: Verify Docker image built successfully
      run: |
        docker images | grep weatherapp
        
    - name: run image
      run: |
          docker run weatherapp
  
