name: ci
on: [push]

jobs:
  lint:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master


  build:
    name: Build Docker Image
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build docker image
        run: |
          docker build -t weatherapp:test .

      - name: Verify Docker image built successfully
        run: |
          docker images | grep weatherapp

      - name: run image
        run: |
          docker run --rm weatherapp:test --name weatherapp -e CITY='$CITY' -e API_KEY='${{ secrets.OPENWEATHER_API_KEY }}'  
